version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angularjs"]
  environment = [
    "nodejs",
    "browser",
    "vitest",
    "jasmine"
  ]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"